### ISSUE TITLE
Allow Rotation Filtering by User 

### ISSUE THREAD

**Issue by paulboehnke** [rl-institut/SimBA#30]
Allowing the user to filter for certain rotations of the input schedule to include in the analysis.

Possible examples:
- Only rotations that start/end at a certain depot
- Only rotations that pass by a certain station
- Only rotations travelling distances smaller/larger than X
... 

Lets discuss which options would be helpful. Also lets talk about how users would input their filter selection into the software.

**Comment by j-brendel** [comment]
closed by #92
