### ISSUE TITLE
Extended output plots

### ISSUE THREAD

**Issue by alexkens** [rl-institut/SimBA#94]
New functions should be in report.py and create extended output plots in 2 ways:

- [x]  flag „extended_output_plots“ in  generate.py

- [ ] extra script called "generate_extended_output_plots.py"

new plots:

- [x] 1:

Format: boxplot
title: Verteilung der Bustypen über die Fahrleistung der Verbrauche in einer Woche
Info: y=Verbrauche [kWh], y=Fahrleistung pro Umlauf [km], Legende=Bustypen

- [x] 2:

Format: Balkendiagramm
Info: Anteil Gelegenheitslader, Depotlader, nicht elektrifizierbar (SOC<0)

- [x] 3:

Format: Lineplot
Ein Plot der Lastgänge je Grid Connector (also jeder GC bekommt eigenen Plot)
Info: Einzelne Graphen für:
        ◦ Gesamt
        ◦ Feed_in
        ◦ Ext_load
        ◦ Charging_stations
Achsen: x=Zeit, y=kW

**Comment by stefansc1** [comment]
Implemented in #191
